version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

volumes:
  pgdata:
